# Generated by Django 5.2.4 on 2025-12-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pphoto',
            name='media',
            field=models.CharField(default='', max_length=100, verbose_name='圖片檔名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='暫無說明', verbose_name='手機說明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nickname',
            field=models.CharField(default='超值優惠', max_length=15, verbose_name='手機名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='售價'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(default=2020, verbose_name='出廠年份'),
        ),
    ]
